### ISSUE TITLE
Add units to all fields

### ISSUE THREAD

**Issue by robroyaus** [russellwwest/bushtracker#1]
As reported in Discord, it can be confusing to use the BushDiverTracker app to accept a flight because fuel and cargo weights don't match between the app and the sim.  This is particularly likely when your sim settings are metric (kg and litres) because the BushDiverTracker app expects pounds and gallons.

Adding the units (lb, gal) for all entry fields would be a simple way to signpost which units are expected.

For bonus points, add text saying something like "Please select "U.S. System" in Options | General Options | Misc | International Settings"

**Comment by scott-t** [comment]
Should be more-or-less handled by #7 I think. SimConnect doesn't expose the settings in question but is now toggleable via the tracker UI.

@russellwwest can probably mark this as closed/completed?
